name = "temp-mail-service"
main = "src/index.ts"
compatibility_date = "2024-11-11"
kv_namespaces = [
    { binding = "POST_DB", id = "b1002ec7a3d74b9cb64504ea6d6a5586", preview_id = "238c3081e8ae49f091c08df88cf6c079" },
]
