name = "fakemail"
main = "./dist/_worker.js"
compatibility_date = "2025-01-14"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
    { binding = "POST_DB", id = "b1002ec7a3d74b9cb64504ea6d6a5586", preview_id = "238c3081e8ae49f091c08df88cf6c079" },
]

d1_databases = [
    { binding = "MAIL_DB", database_name = "fake-mail", database_id = "852bdefb-ec72-4589-8de3-f49bb2d01883", preview_database_id = "686ae900-aaea-4c69-8499-b0c8ea8c960d"},
]

[vars]
PUBLIC_TURNSTILE_SITE_KEY="0x4AAAAAAA4rlXXIP3FANjmG"
SECRET_KEY="xxx"
PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_xxxx"
CLERK_SECRET_KEY="sk_test_xxxx"
PUBLIC_CLERK_SIGN_IN_URL="/sign-in"
PUBLIC_CLERK_SIGN_UP_URL="/sign-up"


# npx wrangler d1 create fake-mail
# npx wrangler d1 execute fake-mail --local --file=./email-platform-schema.sql
# npx wrangler d1 execute fake-mail --local --command="SELECT COUNT(*) FROM user_email_addresses"
